"""initial postgres schema

Revision ID: f74f527ed314
Revises: 
Create Date: 2026-07-20 15:53:32.532898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f74f527ed314'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('custom_role_limits',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channels_limit', sa.Integer(), nullable=False),
    sa.Column('channels_time', sa.Integer(), nullable=False),
    sa.Column('roles_limit', sa.Integer(), nullable=False),
    sa.Column('roles_time', sa.Integer(), nullable=False),
    sa.Column('links_limit', sa.Integer(), nullable=False),
    sa.Column('links_time', sa.Integer(), nullable=False),
    sa.Column('webhooks_limit', sa.Integer(), nullable=False),
    sa.Column('webhooks_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('custom_user_limits',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channels_limit', sa.Integer(), nullable=False),
    sa.Column('channels_time', sa.Integer(), nullable=False),
    sa.Column('roles_limit', sa.Integer(), nullable=False),
    sa.Column('roles_time', sa.Integer(), nullable=False),
    sa.Column('links_limit', sa.Integer(), nullable=False),
    sa.Column('links_time', sa.Integer(), nullable=False),
    sa.Column('webhooks_limit', sa.Integer(), nullable=False),
    sa.Column('webhooks_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('guild_configs',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('tuner_category_id', sa.BigInteger(), nullable=True),
    sa.Column('tuner_channel_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('guild_limits',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_create_count', sa.Integer(), nullable=True),
    sa.Column('channel_create_time', sa.Integer(), nullable=True),
    sa.Column('channel_delete_count', sa.Integer(), nullable=True),
    sa.Column('channel_delete_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('guild_log_channels',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_create_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_delete_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_update_id', sa.BigInteger(), nullable=True),
    sa.Column('links_spam_id', sa.BigInteger(), nullable=True),
    sa.Column('webhooks_id', sa.BigInteger(), nullable=True),
    sa.Column('bot_joins_id', sa.BigInteger(), nullable=True),
    sa.Column('message_edit_delete_id', sa.BigInteger(), nullable=True),
    sa.Column('voice_move_id', sa.BigInteger(), nullable=True),
    sa.Column('role_updates_id', sa.BigInteger(), nullable=True),
    sa.Column('bans_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('guild_roles',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('quarantine_id', sa.BigInteger(), nullable=True),
    sa.Column('quarantine_alt_id', sa.BigInteger(), nullable=True),
    sa.Column('server_booster_id', sa.BigInteger(), nullable=True),
    sa.Column('ai_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('server_owners',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.create_table('tracked_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracked_users')
    op.drop_table('server_owners')
    op.drop_table('guild_roles')
    op.drop_table('guild_log_channels')
    op.drop_table('guild_limits')
    op.drop_table('guild_configs')
    op.drop_table('custom_user_limits')
    op.drop_table('custom_role_limits')
    op.drop_table('admins')
    # ### end Alembic commands ###
